[workspace]
members = [
  "notecalc-lib",
  "frontend-web",
  "benchmarks",
]

[profile.release]
lto = true
# debug = true

[profile.release.package.frontend-web]
opt-level = "s" # Tell `rustc` to optimize for small code size.
