[package]
name = "benchmarks"
version = "0.1.0"
authors = ["bbodi <bodidev@gmail.com>"]
edition = "2018"


[dependencies]
notecalc-lib = { path = "../notecalc-lib", features = [] }
# tracy-client = { version = "0.10.0", features = ["enable"] }